import {
  normalIconPlain,
  fightingIconPlain,
  flyingIconPlain,
  poisonIconPlain,
  groundIconPlain,
  rockIconPlain,
  bugIconPlain,
  ghostIconPlain,
  steelIconPlain,
  fireIconPlain,
  waterIconPlain,
  grassIconPlain,
  electricIconPlain,
  psychicIconPlain,
  iceIconPlain,
  dragonIconPlain,
  darkIconPlain,
  fairyIconPlain,
  normalIconGo,
  fightingIconGo,
  flyingIconGo,
  poisonIconGo,
  groundIconGo,
  rockIconGo,
  bugIconGo,
  ghostIconGo,
  steelIconGo,
  fireIconGo,
  waterIconGo,
  grassIconGo,
  electricIconGo,
  psychicIconGo,
  iceIconGo,
  dragonIconGo,
  darkIconGo,
  fairyIconGo,
  normalIconMaster,
  fightingIconMaster,
  flyingIconMaster,
  poisonIconMaster,
  groundIconMaster,
  rockIconMaster,
  bugIconMaster,
  ghostIconMaster,
  steelIconMaster,
  fireIconMaster,
  waterIconMaster,
  grassIconMaster,
  electricIconMaster,
  psychicIconMaster,
  iceIconMaster,
  dragonIconMaster,
  darkIconMaster,
  fairyIconMaster,
} from "../assets/assets";

const typeIconMap = {
  normal: normalIconPlain,
  fighting: fightingIconPlain,
  flying: flyingIconPlain,
  poison: poisonIconPlain,
  ground: groundIconPlain,
  rock: rockIconPlain,
  bug: bugIconPlain,
  ghost: ghostIconPlain,
  steel: steelIconPlain,
  fire: fireIconPlain,
  water: waterIconPlain,
  grass: grassIconPlain,
  electric: electricIconPlain,
  psychic: psychicIconPlain,
  ice: iceIconPlain,
  dragon: dragonIconPlain,
  dark: darkIconPlain,
  fairy: fairyIconPlain,
};

const goTypeIconMap = {
  normal: normalIconGo,
  fighting: fightingIconGo,
  flying: flyingIconGo,
  poison: poisonIconGo,
  ground: groundIconGo,
  rock: rockIconGo,
  bug: bugIconGo,
  ghost: ghostIconGo,
  steel: steelIconGo,
  fire: fireIconGo,
  water: waterIconGo,
  grass: grassIconGo,
  electric: electricIconGo,
  psychic: psychicIconGo,
  ice: iceIconGo,
  dragon: dragonIconGo,
  dark: darkIconGo,
  fairy: fairyIconGo,
};

const masterTypeIconMap = {
  normal: normalIconMaster,
  fighting: fightingIconMaster,
  flying: flyingIconMaster,
  poison: poisonIconMaster,
  ground: groundIconMaster,
  rock: rockIconMaster,
  bug: bugIconMaster,
  ghost: ghostIconMaster,
  steel: steelIconMaster,
  fire: fireIconMaster,
  water: waterIconMaster,
  grass: grassIconMaster,
  electric: electricIconMaster,
  psychic: psychicIconMaster,
  ice: iceIconMaster,
  dragon: dragonIconMaster,
  dark: darkIconMaster,
  fairy: fairyIconMaster,
};

export { typeIconMap, goTypeIconMap, masterTypeIconMap };
